(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["brands"],{

/***/ "./src/routes/brands.svelte":
/*!**********************************!*\
  !*** ./src/routes/brands.svelte ***!
  \**********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/routes/brands.svelte generated by Svelte v3.6.4 */


const file = "src/routes/brands.svelte";

function create_fragment(ctx) {
	var t0, h2, t1, t2, section0, h30, t3, t4, p0, t5, t6, p1, t7, t8, div0, t9, section1, h31, t10, t11, p2, t12, t13, p3, t14, t15, div1, t16, section2, h32, t17, t18, p4, t19, t20, div2, t21, section3, h33, t22, t23, p5, t24, t25, div3, t26, div4, img0, t27, img1, t28, img2, t29, img3, t30, img4, t31, img5, t32, img6, t33, img7;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Our brands");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			h30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Mistral");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("A brand started in 2008 by father and daughter duo John and Tracey.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Their products are designed in-house, with prints inspired by the country, town and sea. Versatility, attention to detail and a carefully selected colour palette make Mistral a key brand for women.");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			h31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Braintree");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("A natural clothing company based in London.");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Their philosophy is to design and make beautiful, timeless fashion while caring for the environment. They have been championing sustainable eco fibres such as hemp, bamboo and organic cotton since the mid 1990s. Their quality affordable garments are always produced ethically.");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			h32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Saskia");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("A design house producing a selection of separates from high quality jersey, silk velvet and chiffon in flattering shapes, ideal for the party season!");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			h33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Ochre");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("They design beautiful ranges of one size coloured knitwear in  cashmere and cotton blends.");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			img7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H2", {}, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Our brands");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			section0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", {}, false);
			var section0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section0);

			h30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section0_nodes, "H3", {}, false);
			var h30_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h30);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h30_nodes, "Mistral");
			h30_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section0_nodes, "\n\t");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section0_nodes, "P", {}, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "A brand started in 2008 by father and daughter duo John and Tracey.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section0_nodes, "\n\t");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section0_nodes, "P", {}, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Their products are designed in-house, with prints inspired by the country, town and sea. Versatility, attention to detail and a carefully selected colour palette make Mistral a key brand for women.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			section0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			section1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", {}, false);
			var section1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section1);

			h31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section1_nodes, "H3", {}, false);
			var h31_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h31);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h31_nodes, "Braintree");
			h31_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section1_nodes, "\n\t");

			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section1_nodes, "P", {}, false);
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);

			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "A natural clothing company based in London.");
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section1_nodes, "\n\t");

			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section1_nodes, "P", {}, false);
			var p3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p3);

			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p3_nodes, "Their philosophy is to design and make beautiful, timeless fashion while caring for the environment. They have been championing sustainable eco fibres such as hemp, bamboo and organic cotton since the mid 1990s. Their quality affordable garments are always produced ethically.");
			p3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			section1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			section2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", {}, false);
			var section2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section2);

			h32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section2_nodes, "H3", {}, false);
			var h32_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h32);

			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h32_nodes, "Saskia");
			h32_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section2_nodes, "\n\t");

			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section2_nodes, "P", {}, false);
			var p4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p4);

			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p4_nodes, "A design house producing a selection of separates from high quality jersey, silk velvet and chiffon in flattering shapes, ideal for the party season!");
			p4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			section2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			section3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", {}, false);
			var section3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section3);

			h33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section3_nodes, "H3", {}, false);
			var h33_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h33);

			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h33_nodes, "Ochre");
			h33_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(section3_nodes, "\n\t");

			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section3_nodes, "P", {}, false);
			var p5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p5);

			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p5_nodes, "They design beautiful ranges of one size coloured knitwear in  cashmere and cotton blends.");
			p5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			section3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img0);

			img0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img1);

			img1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img2);

			img2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img3);

			img3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img4);

			img4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img5);

			img5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img6);

			img6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n\t");

			img7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "IMG", { alt: true, src: true }, false);
			var img7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img7);

			img7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "About";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 4, 0, 52);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h30, file, 7, 1, 86);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 8, 1, 106);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 11, 1, 188);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section0, file, 6, 0, 75);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div0, "class", "divider");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 16, 0, 410);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h31, file, 19, 1, 450);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 20, 1, 472);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p3, file, 23, 1, 530);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section1, file, 18, 0, 439);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div1, "class", "divider");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 28, 0, 831);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h32, file, 31, 1, 871);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p4, file, 32, 1, 890);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section2, file, 30, 0, 860);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div2, "class", "divider");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 37, 0, 1064);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h33, file, 40, 1, 1104);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p5, file, 41, 1, 1122);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section3, file, 39, 0, 1093);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div3, "class", "divider");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 46, 0, 1237);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "alt", "brand-image-braintree");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img0, "src", "assets/brand_logos/color/braintree.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img0, file, 49, 1, 1298);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "alt", "brand-image-kris-ana");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img1, "src", "assets/brand_logos/color/kris-ana.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img1, file, 50, 1, 1378);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img2, "alt", "brand-image-lilyandme");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img2, "src", "assets/brand_logos/color/lilyandme.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img2, file, 51, 1, 1456);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img3, "alt", "brand-image-mistral");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img3, "src", "assets/brand_logos/color/mistral.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img3, file, 52, 1, 1536);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img4, "alt", "brand-image-ochre");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img4, "src", "assets/brand_logos/color/ochre.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img4, file, 53, 1, 1612);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img5, "alt", "brand-image-saskia");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img5, "src", "assets/brand_logos/color/saskia.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img5, file, 54, 1, 1684);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img6, "alt", "brand-image-tempest");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img6, "src", "assets/brand_logos/color/tempest.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img6, file, 55, 1, 1758);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img7, "alt", "brand-image-treaty");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(img7, "src", "assets/brand_logos/color/treaty.jpg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img7, file, 56, 1, 1834);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(div4, "class", "img-brand-holder");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 48, 0, 1266);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, h2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, section0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section0, h30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h30, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section0, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section0, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t8, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t9, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, section1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section1, h31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h31, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section1, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section1, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p2, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section1, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section1, p3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p3, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t15, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t16, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, section2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section2, h32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h32, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section2, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section2, p4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p4, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t20, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t21, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, section3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section3, h33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h33, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section3, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(section3, p5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p5, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t25, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t26, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t29);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, img7);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(h2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(section0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t8);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t9);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(section1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t15);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div1);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t16);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(section2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t20);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t21);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(section3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t25);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div3);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t26);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div4);
			}
		}
	};
}

class Brands extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Brands);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiI2NDhkYjM3MjE4NzNiNmJkZWUzZS9icmFuZHMuYnJhbmRzLmpzIiwic291cmNlc0NvbnRlbnQiOltdLCJzb3VyY2VSb290IjoiIn0=